const COLOURS = [];

COLOURS.TEXT_COLOUR_LIGHT = "#213555";
COLOURS.TEXT_COLOUR_DARK = "#FEF9F2";

COLOURS.SPECIAL_TEXT_COLOUR_LIGHT = '#9268A5'
COLOURS.SPECIAL_TEXT_COLOUR_DARK = '#67d6f3'

COLOURS.ICON_COLOUR_LIGHT = "#F3C623";
COLOURS.ICON_COLOUR_DARK = "#FEF9F2";

COLOURS.BACKGROUND_LIGHT = '#FFFFFF';
COLOURS.BACKGROUND_DARK = '#000000';

COLOURS.SECTION_COLOUR_DARK = '#222'
COLOURS.SECTION_COLOUR_LIGHT = '#f5f5f5'

COLOURS.MENU_COLOURS_LIGHT = [
    "#CA3E6B", // Education
    "#FA8383", // Projects
    "#9DD3CC", // Work Experience
];
COLOURS.MENU_COLOURS_DARK = [
    "#00A9E0",  // Electric Blue (for Education)
    "#FFEA00",  // Bright Yellow (for Projects)
    "#FF6B6B",  // Soft Coral (for Work Experience)
];

export default COLOURS;
